---

- name: Install nginx
  apt:
   name: nginx
   state: present

- name: Insert Index Page
  template:
   src: /root/.jenkins/workspace/Devops_301_demo/index.html
   dest: /var/www/html/index.html
  notify:
  - restart nginx
      
