---
#this playbook is to install tomcat.
  - name: Download Tomcat
    get_url: url=https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.10/bin/apache-tomcat-9.0.10.tar.gz dest=/opt/SP/apps/tomcat.tar.gz mode=0755 

  - name: Extract Tomcat
    command: "tar zxf /opt/SP/apps/tomcat.tar.gz  -C /opt/SP/apps/tomcat --strip-components 1"
   
  - name: Download WAR to server
    synchronize: src=/root/.jenkins/workspace/Devops_301_demo/target/devops-0.0.1-SNAPSHOT.war dest=/opt/SP/apps/tomcat/webapps/ROOT/ 

  - name: Unzip WAR file
    unarchive: src=/opt/SP/apps/tomcat/webapps/ROOT/devops-0.0.1-SNAPSHOT.war dest=/var/lib/tomcat7/webapps/ROOT/ copy=no mode=0755 owner=tomcat7 group=tomcat7
    notify:
        - Restart tomcat7

  - name: Delete remote war file
    file: path=/opt/SP/apps/tomcat/webapps/ROOT/devops-0.0.1-SNAPSHOT.war state=absent
